#!/usr/bin/env python3
"""Generate an ESP-IDF x509_crt_bundle C source from a Mozilla cacert.pem.

Bundle layout (big-endian, matches esp_crt_bundle.c in arduino-esp32):
  uint16 num_certs
  per cert: uint16 name_len, uint16 key_len, name(DER), key(SPKI DER)

Entries are sorted by `name` bytes because esp_crt_bundle_init() binary-searches
on the child certificate's issuer_raw DER. The C parser advances each entry by
exactly 4 + name_len + key_len, so no trailing certificate DER may be stored.
Pure stdlib, no external deps.
"""

import argparse
import base64
import re


def read_tlv(data, i):
    tag = data[i]
    i += 1
    length = data[i]
    i += 1
    if length & 0x80:
        n = length & 0x7F
        if n > 4 or i + n > len(data):
            raise ValueError("bad long-form length")
        length = int.from_bytes(data[i:i + n], "big")
        i += n
    if length < 0 or i + length > len(data):
        raise ValueError("length out of range")
    return tag, length, i, i + length


def split_elements(data, start, end):
    out = []
    pos = start
    while pos < end:
        tag, length, content_start, content_end = read_tlv(data, pos)
        out.append((tag, length, content_start, content_end, pos, content_end))
        pos = content_end
    return out


def cert_subject_spki(der):
    """Return (subject_raw_der, spki_raw_der) for an X.509 DER certificate."""
    tag, _, tbs_pos, tbs_end = read_tlv(der, 0)  # Certificate SEQUENCE
    if tag != 0x30:
        raise ValueError("not a DER certificate")
    elems = split_elements(der, tbs_pos, tbs_end)
    # elems[0] = tbsCertificate SEQUENCE
    tag, _, inner_pos, inner_end = elems[0][0], elems[0][1], elems[0][2], elems[0][3]
    if tag != 0x30:
        raise ValueError("bad tbsCertificate")
    inner = split_elements(der, inner_pos, inner_end)
    idx = 0
    # [0] EXPLICIT version is optional
    if inner[idx][0] == 0xA0:
        idx += 1
    # serialNumber INTEGER
    if inner[idx][0] != 0x02:
        raise ValueError("bad serial")
    idx += 1
    # signature AlgorithmIdentifier SEQUENCE
    if inner[idx][0] != 0x30:
        raise ValueError("bad signature alg")
    idx += 1
    # issuer Name SEQUENCE
    if inner[idx][0] != 0x30:
        raise ValueError("bad issuer")
    idx += 1
    # validity SEQUENCE
    if inner[idx][0] != 0x30:
        raise ValueError("bad validity")
    idx += 1
    # subject Name SEQUENCE (raw DER including tag+length)
    subject_raw = der[inner[idx][4]:inner[idx][5]]
    idx += 1
    # subjectPublicKeyInfo SEQUENCE (raw DER including tag+length)
    spki_raw = der[inner[idx][4]:inner[idx][5]]
    return subject_raw, spki_raw


PEM_RE = re.compile(
    r"-----BEGIN CERTIFICATE-----(.*?)-----END CERTIFICATE-----", re.S)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("input", help="path to cacert.pem")
    ap.add_argument("out_h", help="output header path")
    ap.add_argument("out_cpp", help="output source path")
    args = ap.parse_args()

    with open(args.input, "r", encoding="utf-8") as f:
        pem = f.read()

    entries = []
    seen = set()
    for match in PEM_RE.finditer(pem):
        der = base64.b64decode(re.sub(r"\s+", "", match.group(1)))
        try:
            name, key = cert_subject_spki(der)
        except ValueError as exc:
            print(f"skip cert: {exc}")
            continue
        if name in seen:
            continue
        seen.add(name)
        entries.append((name, key))

    entries.sort(key=lambda e: e[0])
    print(f"parsed {len(entries)} unique certificates")

    total = 2 + sum(4 + len(n) + len(k) for n, k in entries)
    print(f"bundle size: {total} bytes")

    with open(args.out_h, "w", encoding="utf-8") as f:
        f.write("#pragma once\n")
        f.write("#include <stddef.h>\n")
        f.write("#include <stdint.h>\n")
        f.write(f"#define X509_CRT_BUNDLE_LEN {total}\n")
        f.write("extern const uint8_t x509_crt_bundle[X509_CRT_BUNDLE_LEN];\n")

    with open(args.out_cpp, "w", encoding="utf-8") as f:
        f.write('// Generated by tools/gen_crt_bundle.py from Mozilla cacert.pem. Do not edit.\n')
        f.write('#include "cert_bundle.h"\n\n')
        f.write("const uint8_t x509_crt_bundle[X509_CRT_BUNDLE_LEN] = {\n")
        f.write(f"  {len(entries) >> 8}, {len(entries) & 0xFF},\n")
        line = []
        for name, key in entries:
            for byte in (
                    bytes([len(name) >> 8, len(name) & 0xFF])
                    + bytes([len(key) >> 8, len(key) & 0xFF])
                    + name + key):
                line.append(str(byte))
                if len(line) == 16:
                    f.write("  " + ",".join(line) + ",\n")
                    line = []
        if line:
            f.write("  " + ",".join(line) + ",\n")
        f.write("};\n")


if __name__ == "__main__":
    main()
